### ISSUE TITLE
Investigate JSX support

### ISSUE THREAD

**Issue by bryanjos** [elixirscript/elixirscript#153]
JSX support could come in the form of:
- updating the current Html module to keep the same functions, but compile to jsx code
- Adding a sigil that takes jsx.
- insert suggestion here

The issues with the sigil may be trying to implement jsx interpolation. More investigation would need to take place on if it's possible

``` elixir
~j(<div>Hello {props.name}</div>)
```

**Comment by bryanjos** [comment]
Just going to through some ideas out:

```elixir
jsx(:div, [class: "test"], [
  jsx(MyComponent, [key: value])
])
```


```elixir
Html.div [class: "test"] do
  Html.component MyComponent, [key: value])
end
```

**Comment by AdamBrodzinski** [comment]
This is interesting, it reminds me of Elm HTML. However, I also personally find Elm HTML to breakdown with readability with larger HTML blocks.

Having a sigil would really be ideal:

```
def render(props) do
  ~j(
    <div>
      Hello {props.name}
    </div>
   )
end
```


Just my $0.02 :smile:

**Comment by bryanjos** [comment]
That would be nicer, but it would also require parsing the jsx which is going to be a bit more difficult. Maybe it's made easier with an html or xml parser, but then there is figuring out how to add in parts where one can add in code (`{props.name}`). Maybe it would possible to leverage EEx

**Comment by AdamBrodzinski** [comment]
Yea I agree, that makes things much more difficult. On RedScript I was just using hacky regex replacements instead of lexing/parsing so i'm not sure how to do this one. 

However, unless React is just a fad I think it'll be a barrier to clienside ElixirScript.

If using the following is easier, it would still be easier/cleaner:

```
Html.div [class: "test"] do
  Html.component MyComponent, [key: value])
end
```

At any rate I guess JSX wouldn't be the highest of priorities... it's still really cool to write Elixir for the browser :smile:  

One could probably also just write stateless components in JS and then import them... then ElixirScript could be used in business logic/redux/etc... To me this would be the only way I could use it for a sideproject type app (or prod app when it's ready). I do want to experiment a little more with this and RN soon!

**Comment by olafura** [comment]
I think using #{} is going to easiest to implement since the other sigils seem to support it and it is close enough to the other syntax. It's just Macro.unescape_string call away.

**Comment by olafura** [comment]
I'm playing a bit with using erlsom and it's very promissing:
:erlsom.simple_form(Macro.unescape_string("<div class=\"test\">Hello #{:world}</div>"))
{:ok, {'div', [{'class', 'test'}], ['Hello world']}, []}

Now just to do some transformations and it should split out 
Html.div [class: "test"] do: "Hello world"
or Html.div [class: "test"] do: "Hello #{:world}" depending how you are looking at it since it's a macro.

**Comment by olafura** [comment]
Is it safe to use Html.div syntax or is that missing?

**Comment by bryanjos** [comment]
Interesting! 

I took out the existing Html module that used the virtual DOM since with the latest version, one can do the same via macros. Bringing i back to be used for JSX is an option.

What I was thinking was if we allowed someone to write JSX (as JSX) in Elixirscript, translating that to JS and JSX AST, and then generating JSX again with the code blocks that were in elixir into JS.

So a JSX string in Elixirscript would be:
`<div class=\"test\">Hello #{:world}</div>`

And ultimately be translated to:
`<div class=\"test\">Hello {Symbol.for("world")}</div>`

It seems weird but since JSX can be used for more than React it allows for a lot of flexibility.

What erlsom returned could be very useful for doing that

**Comment by AdamBrodzinski** [comment]
I just stumbled across these React Templates that could be useful for using ElixirScript and React together... https://wix.github.io/react-templates. It seems like it also works with React Native based on some of their tests.

This could mean writing all the logic in ElixirScript and then passing it into one of these templates to handle the markup... bypassing the hassle of getting ElixirScript to handle JSX 👍 

Going to try this out soon!

**Comment by bryanjos** [comment]
Interesting! That could definitely be a way to go

**Comment by bryanjos** [comment]
Going to close this since there hasn't been any progress or a way forward on it. If things change it can be reopened and revisited

**Comment by English3000** [comment]
Another way to implement this would be as a tree of structs:

```elixir
defmodule Component do
  @type t :: %Component{props :: %{}, state :: pid, children :: %{}, key :: atom}
end
```

Components would also need to hold their lifecycle methods.

Additionally, as each component (except pure components) spawns a process for its state, `props` should include data about the parent struct.

This implies `Component` should be a behaviour which defines a `Component` struct (which takes the name of the module it is used in), requires a `render` callback and an `init` callback to start a process for state (unless flagged as a purely functional component).

---
_One more question:_ Does ElixirScript work for mobile?

**Comment by AdamBrodzinski** [comment]
@English3000 Yes, I think there's a React Native example app somewhere as well.
