### ISSUE TITLE
Map.get fails if key is tuple or list

### ISSUE THREAD

**Issue by vans163** [elixirscript/elixirscript#406]
```
map = %{[:key, 5]=> 5}
Console.log Map.get(map, [:key, 5])
null

map = %{{:key, 5}=> 5}
Console.log Map.get(map, {:key, 5})
null
```

**Comment by bryanjos** [comment]
When I first saw this I was afraid it would be a lot worse. I think the easiest thing to do for now is to update the maps.js file to handle `get`s and `has`s differently. Instead of relying on JavaScript's Map.get and Map.has, instead the keys can be iterated through and call the custom `equals` function in the erlang.js module to check for equality

**Comment by vans163** [comment]
This is an annoying problem.  Im worried the cost will be very high to iterate the map.

A super annoying alternative way to implement this would be hashing the js object and using it as a key, https://github.com/puleos/object-hash.  Then keeping the actual key somewhere near the value, abstracting that away. basically your making your own types at this point to better reflect Erlang types in javascript.
